In [1]:
a = 1; print(type(a))
#a는 variable, =은 assign한다는 의미(equal이 아님), 1은 variable에 assign될 content

<class 'int'>


In [2]:
print(a)

1


In [3]:
b = 2; print(b)

2


In [4]:
print(a)
print(b)
#프린트를 써주는 이유는 output에 제일 마지막 거만이 아니라 둘 다 나오게 하기 위해

1
2


In [18]:
a = 1; a = float(a); print(type(a))
#float은 소수점있는 거, int는 정수

<class 'float'>


In [19]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


In [20]:
a = '123'; print(type(a)); print(a[1])
#[1]은 순서, python은 첫번째가 0, 고로 1은 두번째 element

<class 'str'>
2


In [21]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])
#숫자는 초록, 문자는 빨강, 숫자의 문자화는 single quotation이나 double quotation으로

<class 'list'>
['1', '2', '3']
3


In [22]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


In [23]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


In [24]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


In [ ]:
#[]는 list, ()는 tuple, {}는 dictionary, 항상 사전처럼 정보가 pairwise

In [27]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

In [28]:
#하드디스크에 다운 받은 것을 메모리에 올려놓는 것이 import이다
import numpy as np
#넘피(library)에 이런 기능이 있다라는 것을 알고 써줘야한다 b=array(a)라고 쓰면 오류남 array는 matrix랑 비슷
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


In [29]:
print(b*b)
#곱하기를 했더니 elementxelement로 곱해지는 걸 보면 진짜 행렬이 아니다 원래 행렬은 2x3, 3x2형태만 곱해짐

[[ 1  4  9]
 [ 9 64  0]]


In [30]:
c = np.matrix(b)
#진짜 matrix로 바꾸기 위한 함수
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [31]:
c*c 
#에러가 뜬 이유는 진짜 행렬이라서 곱이 성립이 안 되기 때문

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [32]:
c*c.T
#t는 transpose.  그래서 곱해지면 2by2행렬이 나옴

matrix([[14, 19],
        [19, 73]])

In [1]:
s = 'abcdef'

In [3]:
print(type(s))

<class 'str'>
